// Generated by scripts/update-repository-stars.mjs. Do not edit manually.
export const repositoryStarsUpdatedAt = '2026-09-25T08:53:05.811Z'

export const repositoryStars = {
  'blitzstrike': 529,
  'strix': 64689,
  'impeccable': 70882,
  '9router': 29774,
  'viserys-agent': 589,
}
