// Generated by scripts/update-repository-stars.mjs. Do not edit manually.
export const repositoryStarsUpdatedAt = '2026-10-10T09:55:01.649Z'

export const repositoryStars = {
  'blitzstrike': 503,
  'strix': 67666,
  'impeccable': 79179,
  '9router': 30544,
  'viserys-agent': 556,
}
