// Generated by scripts/update-repository-stars.mjs. Do not edit manually.
export const repositoryStarsUpdatedAt = '2026-10-04T09:53:37.169Z'

export const repositoryStars = {
  'blitzstrike': 497,
  'strix': 66401,
  'impeccable': 75696,
  '9router': 30264,
  'viserys-agent': 556,
}
